const $ = (s) => document.querySelector(s);
const state = { name:'', userId:localStorage.getItem('izlaUserId')||crypto.randomUUID(), map:null, marker:null, accuracy:null, watching:null, active:false, started:0, points:[], line:null, preview:null, territories:[], distance:0, timer:null, onlineLayers:[], lastSent:0, players:[] };
localStorage.setItem('izlaUserId',state.userId);
const colors = ['#ef3340','#1246d8','#782fd1','#f29c16'];

function toast(msg){ const t=$('#toast'); t.textContent=msg; t.classList.add('show'); clearTimeout(t._x); t._x=setTimeout(()=>t.classList.remove('show'),2600); }
function esc(v){ return v.replace(/[<>]/g,''); }
function hav(a,b){ const R=6371000,p=Math.PI/180,d1=(b[0]-a[0])*p,d2=(b[1]-a[1])*p; const x=Math.sin(d1/2)**2+Math.cos(a[0]*p)*Math.cos(b[0]*p)*Math.sin(d2/2)**2; return 2*R*Math.asin(Math.sqrt(x)); }
function polygonArea(points){ if(points.length<3)return 0; const lat=points.reduce((s,p)=>s+p[0],0)/points.length*Math.PI/180; let sum=0; for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length];sum+=(a[1]*111320*Math.cos(lat))*(b[0]*110540)-(b[1]*111320*Math.cos(lat))*(a[0]*110540)} return Math.abs(sum/2); }

function initMap(center=[41.3111,69.2797]){
  if(state.map)return;
  state.map=L.map('map',{zoomControl:false,attributionControl:true}).setView(center,16);
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap'}).addTo(state.map);
  connectOnline(); renderBoard();
}
function addRivals(c){
  const rivals=[{name:'Sardor',color:colors[1],off:[.0013,.0009],area:2840},{name:'Malika',color:colors[2],off:[-.0011,.0014],area:1920},{name:'Akmal',color:colors[3],off:[.0005,-.0018],area:980}];
  rivals.forEach((r,i)=>{const [x,y]=[c[0]+r.off[0],c[1]+r.off[1]],d=.00045+i*.00008;const pts=[[x-d,y-d],[x+d*.7,y-d*1.1],[x+d,y+d*.55],[x-d*.35,y+d],[x-d*1.1,y+d*.25]];L.polygon(pts,{color:r.color,fillColor:r.color,fillOpacity:.23,weight:2}).addTo(state.map).bindTooltip(r.name,{permanent:true,direction:'center',className:'territory-label'});state.territories.push(r)});
 }
function renderBoard(){ const rows=(state.players.length?state.players:[{name:state.name||'Siz',color:'#ef3340',area:+localStorage.getItem('izlaArea')||0}]).sort((a,b)=>b.area-a.area); $('#leaderRows').innerHTML=rows.map((r,i)=>`<div class="leader-row"><b>${i+1}</b><i style="background:${r.color||colors[i%colors.length]}"></i><span>${esc(r.name)}</span><strong>${Math.round(r.area).toLocaleString()} m²</strong></div>`).join(''); }

function clearOnline(){state.onlineLayers.forEach(l=>l.remove());state.onlineLayers=[]}
function renderOnline(data){
  if(!state.map)return;clearOnline();state.players=data.players||[];
  state.players.forEach((p,idx)=>{const color=p.color||colors[idx%colors.length],all=[];(p.territories||[]).forEach(t=>{const layer=L.polygon(t.points,{color,fillColor:color,fillOpacity:.24,weight:2}).addTo(state.map);state.onlineLayers.push(layer);t.points.forEach(x=>all.push(x))});if(all.length){const center=[all.reduce((s,x)=>s+x[0],0)/all.length,all.reduce((s,x)=>s+x[1],0)/all.length];const size=Math.max(10,Math.min(28,10+Math.sqrt(p.area||0)/14));const label=L.marker(center,{interactive:false,icon:L.divIcon({className:'owner-label',html:`<span style="font-size:${size}px;color:${color}">${esc(p.name)}</span>`})}).addTo(state.map);state.onlineLayers.push(label)}if(p.location&&p.id!==state.userId&&Date.now()-p.location.time<120000){const dot=L.circleMarker([p.location.lat,p.location.lng],{radius:6,color:'#fff',weight:3,fillColor:color,fillOpacity:1}).addTo(state.map).bindTooltip(esc(p.name));state.onlineLayers.push(dot)}});
  const mine=state.players.find(p=>p.id===state.userId);if(mine){$('#totalArea').textContent=Math.round(mine.area).toLocaleString();localStorage.setItem('izlaArea',mine.area)}renderBoard();
}
async function fetchWorld(){try{const r=await fetch('/api/world');if(r.ok)renderOnline(await r.json())}catch{toast('Server bilan aloqa yo‘q — offline rejim')}}
function connectOnline(){fetchWorld();if(!window.EventSource)return;const events=new EventSource('/api/events');events.onmessage=e=>{try{renderOnline(JSON.parse(e.data))}catch{}};events.onerror=()=>events.close()}
async function sendLocation(p){if(!state.name||Date.now()-state.lastSent<3000)return;state.lastSent=Date.now();try{await fetch('/api/location',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:state.userId,name:state.name,lat:p[0],lng:p[1]})})}catch{}}

function onPosition(pos){ const p=[pos.coords.latitude,pos.coords.longitude],acc=pos.coords.accuracy||10; if(!state.map)initMap(p); if(!state.marker){state.marker=L.circleMarker(p,{radius:8,color:'#fff',weight:4,fillColor:'#ef3340',fillOpacity:1}).addTo(state.map);state.accuracy=L.circle(p,{radius:acc,color:'#1246d8',weight:1,fillOpacity:.07}).addTo(state.map);state.map.setView(p,17)} else {state.marker.setLatLng(p);state.accuracy.setLatLng(p).setRadius(acc)} sendLocation(p);if(state.active)addPoint(p); }
function geoError(e){ initMap(); toast(e.code===1?'Joylashuvga ruxsat berilmadi. Telefon sozlamalaridan ruxsat bering.':'Joylashuv aniqlanmadi. GPS yoqilganini tekshiring.'); }
function requestLocation(){ if(!navigator.geolocation){geoError({code:0});return} navigator.geolocation.getCurrentPosition(p=>{onPosition(p);$('#locationModal').classList.remove('active');toast('Joylashuv aniqlandi ✓');},geoError,{enableHighAccuracy:true,timeout:10000}); }
function addPoint(p){ const prev=state.points.at(-1); if(prev&&hav(prev,p)<3)return; if(prev)state.distance+=hav(prev,p); state.points.push(p); if(!state.line)state.line=L.polyline(state.points,{color:'#ef3340',weight:5,opacity:.95,lineJoin:'round'}).addTo(state.map);else state.line.setLatLngs(state.points); if(state.preview)state.preview.remove(); if(state.points.length>2)state.preview=L.polygon(state.points,{color:'#ef3340',weight:1,dashArray:'5 7',fillColor:'#ef3340',fillOpacity:.1}).addTo(state.map); updateStats(); if(state.points.length>8&&hav(state.points[0],p)<18)finishWalk(true); }
function updateStats(){ $('#distance').innerHTML=`${(state.distance/1000).toFixed(2)} <small>km</small>`; const secs=state.active?Math.floor((Date.now()-state.started)/1000):0; $('#timer').textContent=`${String(Math.floor(secs/60)).padStart(2,'0')}:${String(secs%60).padStart(2,'0')}`; const sp=secs?state.distance/secs*3.6:0;$('#speed').innerHTML=`${sp.toFixed(1)} <small>km/soat</small>`; }
function startWalk(){ if(!state.map)initMap(); state.active=true;state.started=Date.now();state.points=[];state.distance=0;if(state.line)state.line.remove();if(state.preview)state.preview.remove();state.line=state.preview=null;$('#startBtn').classList.add('running');$('#startText').textContent='YURISHNI YAKUNLASH';$('#hint').textContent='Boshlagan nuqtangizga qayting';state.timer=setInterval(updateStats,1000);if(navigator.geolocation)state.watching=navigator.geolocation.watchPosition(onPosition,geoError,{enableHighAccuracy:true,maximumAge:1000});toast('Yurish boshlandi — xavfsiz yuring!');}
async function finishWalk(closed=false){ state.active=false;clearInterval(state.timer);if(state.watching!=null)navigator.geolocation.clearWatch(state.watching);$('#startBtn').classList.remove('running');$('#startText').textContent='YURISHNI BOSHLASH';$('#hint').textContent='Boshlagan joyingizga qaytib, hududni yoping';if(state.points.length<3){toast('Hudud yaratish uchun ko‘proq yuring');return}const gap=hav(state.points[0],state.points.at(-1));if(!closed&&gap>35){toast('Hudud yopilmadi — boshlagan nuqtaga qayting');return}const area=Math.round(polygonArea(state.points));if(state.preview)state.preview.remove();$('#areaStatus').textContent=`Yangi hudud: +${area.toLocaleString()} m²`;try{const r=await fetch('/api/territory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:state.userId,name:state.name,points:state.points,area})});if(!r.ok)throw 0;toast(`${area.toLocaleString()} m² hudud hammaga qo‘shildi!`)}catch{L.polygon(state.points,{color:'#ef3340',fillColor:'#ef3340',fillOpacity:.28,weight:3}).addTo(state.map);toast('Server topilmadi — hudud vaqtincha faqat sizda ko‘rinadi')}}
$('#continueBtn').onclick=()=>{const n=$('#nameInput').value.trim();if(!n){$('#nameError').classList.add('show');$('#nameInput').focus();return}state.name=n;localStorage.setItem('izlaName',n);$('#avatarLetter').textContent=n[0].toUpperCase();$('#welcomeModal').classList.remove('active');$('#locationModal').classList.add('active');renderBoard()};
$('#nameInput').onkeydown=e=>{if(e.key==='Enter')$('#continueBtn').click()};$('#nameInput').oninput=()=>$('#nameError').classList.remove('show');
$('#allowBtn').onclick=requestLocation;
$('#startBtn').onclick=()=>state.active?finishWalk():startWalk();$('#locateBtn').onclick=()=>{if(state.marker)state.map.flyTo(state.marker.getLatLng(),17);else requestLocation()};
$('#rankBtn').onclick=()=>$('#leaderboard').classList.toggle('open');$('#closeBoard').onclick=()=>$('#leaderboard').classList.remove('open');
const saved=localStorage.getItem('izlaName');if(saved){state.name=saved;$('#nameInput').value=saved;$('#avatarLetter').textContent=saved[0].toUpperCase()}$('#totalArea').textContent=Math.round(+localStorage.getItem('izlaArea')||0).toLocaleString();
